name: pet-guild
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/afdal595/pets.git
    build_command: composer install --no-dev && npm install && npm run build
    run_command: heroku-php-apache2 public/
    envs:
      - key: APP_NAME
        value: "Pet Guild"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:zNwgEXfuU5xEvaJiqmLf3HCTvmPrJj6/U5cqLxaxv/I="
      - key: APP_URL
        value: ${_self.PUBLIC_URL}
      - key: DB_CONNECTION
        value: mysql
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: database
